services:
  user_naming.importexport.data_converter.user_naming_alias:
    parent: oro_importexport.data_converter.configurable

  user_naming.importexport.data_converter.template_fixture.user_naming_alias:
    parent: oro_importexport.data_converter.template_fixture.configurable

  user_naming.importexport.strategy.user_naming_alias.add_or_replace:
    parent: oro_importexport.strategy.configurable_add_or_replace

  user_naming.importexport.processor.export.user_naming_alias:
    parent: oro_importexport.processor.export_abstract
    calls:
      - [setDataConverter, ['@user_naming.importexport.data_converter.user_naming_alias']]
    tags:
      -
        name: oro_importexport.processor
        type: export
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_alias

  user_naming.importexport.processor.export_template.user_naming_alias:
    parent: oro_importexport.processor.export_abstract
    calls:
      - [setDataConverter, ['@user_naming.importexport.data_converter.template_fixture.user_naming_alias']]
    tags:
      -
        name: oro_importexport.processor
        type: export_template
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_alias

  user_naming.importexport.processor.import.user_naming_alias:
    parent: oro_importexport.processor.import_abstract
    calls:
      - [setDataConverter, ['@user_naming.importexport.data_converter.user_naming_alias']]
      - [setStrategy, ['@user_naming.importexport.strategy.user_naming_alias.add_or_replace']]
    tags:
      -
        name: oro_importexport.processor
        type: import
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_alias_add_or_replace
      -
        name: oro_importexport.processor
        type: import_validation
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_alias_add_or_replace

  Training\Bundle\UserNamingBundle\ImportExport\TemplateFixture\UserNamingTypeFixture:
    tags: [oro_importexport.template_fixture]

  Training\Bundle\UserNamingBundle\ImportExport\Configuration\UserNamingImportExportConfigurationProvider:
    tags:
      - { name: oro_importexport.configuration, alias: user_naming }
